version: '2.1'

services:
  adoption-backend:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/adoption/backend
    environment:
      - IDAM_API_URL=http://idam-api:5000
      - CORE_CASE_DATA_API_URL=http://ccd-data-store-api:4452
      - IDAM_S2S_AUTH_URL=http://service-auth-provider-api:8080
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - $SERVER_PORT:$SERVER_PORT
    networks:
      - default
      - ccd-network
networks:
  ccd-network:
    external: true