server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: adoption-backend

idam:
  s2s-auth:
    microservice: adoption

---

spring:
  profiles: local
  main:
    allow-bean-definition-overriding: true
  security:
    enabled: false
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://fr-am:8080/openam/oauth2/hmcts
          jwk-set-uri: http://localhost:5000/o/jwks

idam:
  api:
    url: http://localhost:5000
  s2s-auth:
    url: http://localhost:4502
    totp_secret: AABBCCDDEEFFGGHH
  client:
    id: adoption
    redirect_uri: https://localhost:9000/oauth2/callback
    secret: OOOOOOOOOOOOOOOO

auth:
  idam:
    client:
      baseUrl: http://localhost:5000
  provider:
    service:
      client:
        baseUrl: http://localhost:4502

core_case_data:
  api:
    url: http://localhost:4452

gateway:
  url: http://localhost:3453


